version: 2
jobs:
  build:
    # We use the Node 10.15.1 Docker image
    docker:
      - image: circleci/node:10.15.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install dependencies
      - run: yarn install

      # Cache all node_modules to speed up builds
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run linter to check for code style errors
      - run: yarn run lint

      # Run tests
      - run: yarn test
